name: "Lint"

on:
  # Run this workflow on master always
  push:
    branches:
      - master
  # Run this workflow on PRs that target master,
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(toJson(github.event.commits), '[skip ci]') == false && contains(toJson(github.event.commits), '[ci skip]') == false

    steps:
    - uses: actions/checkout@v1
      with:
        ref: refs/pull/${{ github.event.number }}/head
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Lint
      run: yarn lint
      